---
title: "Pull and Tidy"
date: "11/6/2020"
output: 
  github_document:
  always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(httr)
library(purrr)
library(leaflet)
```


```{r import MV crash, include=FALSE}
#Importing crash data using the NYC Open Data API. The API response is limited to 50,000 rows, so we need a function that can be used to page through these results to capture all crashes in 2020. 

crash_api_2019a = function(offset) {
  GET("https://data.cityofnewyork.us/resource/h9gi-nx95.csv", 
      query = list("$where" = "crash_date between '2019-01-01T00:00:00' and '2019-5-31T12:00:00'", "$limit" = 50000, "$offset" = offset)) %>% 
  content("parsed") %>%
  as_tibble() 
}
crash_api_2019b = function(offset) {
  GET("https://data.cityofnewyork.us/resource/h9gi-nx95.csv", 
      query = list("$where" = "crash_date between '2019-06-01T00:00:00' and '2019-10-31T12:00:00'", "$limit" = 50000, "$offset" = offset)) %>% 
  content("parsed") %>%
  as_tibble() 
}

crash_api_2020 = function(offset) {
  GET("https://data.cityofnewyork.us/resource/h9gi-nx95.csv", 
      query = list("$where" = "crash_date between '2020-01-01T00:00:00' and '2020-10-31T12:00:00'", "$limit" = 50000, "$offset" = offset)) %>% 
  content("parsed") %>%
  as_tibble() 
}

offsets = c(0, 50000)
crash_dat = bind_rows(map_df(offsets, crash_api_2019a), 
                      map_df(offsets, crash_api_2019b),
                      map_df(offsets, crash_api_2020))
```


```{r, tidy MV crash}
#cleaning - transpose so vehicle types are listed in one column
crash_dat = 
  crash_dat %>% 
  separate(crash_date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(year=as.integer(year),
         month=as.integer(month),
         day=as.integer(day)) %>%
  pivot_longer(
    vehicle_type_code1:vehicle_type_code_5,
    names_to = "vehicle_number",
    values_to = "vehicle_options"
   ) %>%
  drop_na(vehicle_options)
```

```{r filtering for microvehicles}
#Exploring the vehicle types so that we can limit to bicycles -- double check this list
bikes = crash_dat %>%
  filter(str_detect(vehicle_options, "[Bb]ike") | 
           str_detect(vehicle_options, "REVEL") | 
           str_detect(vehicle_options, "SCO")  |
           str_detect(vehicle_options, "MOP")   |
           str_detect(vehicle_options, "ELEC")  |
           str_detect(vehicle_options, "^E-")) %>% 
  filter(vehicle_options != "ESCOVATOR" & vehicle_options != "Bike" &
      str_detect(vehicle_options, "Dirt", negate = TRUE),
      str_detect(vehicle_options, "[Mm]otorbike", negate = TRUE)
           ) 
           
#Run to check what the filter ^ resulted in 
# bikes %>% 
#   group_by(vehicle_options) %>% 
#   count() %>% View()
```



Microvehicle incidents in NYC _ a leaflet map
```{r, include=FALSE}
bikes %>%
  drop_na(c(latitude, longitude)) %>% 
   filter(latitude > 40) %>% #filter on this to get rid of lat/longitude with values of (0,0)
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(~longitude, ~latitude, radius = 1)
```


```{r lm for injuries by month}

fit_injuries_month = crash_dat %>%
  group_by(year) %>%
  mutate(year_2020 = year-2019) %>%
  nest(data = -month) %>%
  mutate(models = map(data, ~glm(number_of_persons_injured ~ year_2020 + borough,
                                 family = "poisson", data = .x)),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest(models) %>%
  select(month, term, estimate, std.error, p.value) %>% 
  mutate(term = str_replace(term, "^borough", "Borough: "),
         term = str_replace(term, "year_2020", "2020 v. 2019"),
         month = month.abb[month]) 

fit_injuries_month

```

```{r plot injuries by month}

fit_injuries_month %>% 
  filter(term == "2020 v. 2019") %>%
  ggplot(aes(x = month, y = exp(estimate))) + geom_point() +
  geom_errorbar(aes(ymin = exp(estimate - (1.96*std.error)), 
                    ymax = exp(estimate + (1.96*std.error)))) +
  labs(
    title = "Rate of Injuries Per Month in 2020 v. 2019",
    x = "Month",
    y = "2020 v. 2019 Difference"
  ) 

```




```{r line plot of crashes over time}
#for the line plot, we will want a summary of the number of bike crashes by day. The collisions variable calculates the number of unique crashes and the bikes variable calculates the total number of bikes that crashed (there can be mutliple bikes involved in one crash but this is rare)
crash_date_summ = 
  crash_dat %>%
  filter(str_detect(vehicle_options, "[Bb]ike")) %>%
  group_by(year, month, day) %>%
  summarize(
    collisions = n_distinct(collision_id),
    bikes = n()
  )


#simple plot just to see what the data look like
crash_date_summ %>%
  ggplot(aes(x = paste(month, day, sep="-"), y = collisions, 
             group = year, color = as.factor(year))) +
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  labs(
    title = "Number of Collisions Over Time in January-October of 2019 and 2020",
    x = "Month and Day",
    y = "Number of Collisions"
    ) +
  theme(text = element_text(size = 15), 
        axis.text.x = element_text(angle = 90, hjust=1, size=10)) +
  scale_colour_discrete("Year")
```



```{r import bikes}
#Importing bike data using the NYC Open Data API. The API response is limited to 50,000 rows, so we need a function that can be used to page through these results to capture all bike counts in 2020. 
bike_api = function(offset) {
  GET("https://data.cityofnewyork.us/resource/uczf-rk3c.csv", 
      query = list("$where" = "date between '2020-01-01T00:00:00' and '2020-10-31T12:00:00'", "$limit" = 50000, "$offset" = offset)) %>% 
  content("parsed") %>%
  as_tibble() 
}

offsets = c(0, 50000, 100000, 150000, 200000, 250000, 300000, 350000, 400000)
bike_dat_2020 = map_df(offsets, bike_api)
```



```{r tidy bikes}

# Make df with aggregate bike counts by day. I noticed that there are some days with NAs - haven't explored yet but might want to look into if the bike counting operation itself was limited at all by covid.
bike_counts_aggregate = 
  bike_dat_2020 %>% 
  mutate(
    date_time = date,
    date = lubridate::date(date_time)
  ) %>% 
  group_by(date) %>% 
  summarize(total_daily_bikes = sum(counts, na.rm = TRUE))

# Look at simple graph of bike counts by day, analagous to the one of crashes above.
bike_counts_aggregate %>%
  ggplot(aes(x = date, y = total_daily_bikes)) +
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE)
```


