---
title: "Microvehicles & Bike Incidents in NYC"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
    always_allow_html: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(httr)
library(purrr)
library(leaflet)
library(plotly)
library(flexdashboard)


knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
# setting user, api key and access token
Sys.setenv("plotly_username"="aabramov90")

Sys.setenv("plotly_api_key"="TcaNTrLIJVEJyrUlhXgd")

Sys.setenv('MAPBOX_TOKEN' = 'pk.eyJ1IjoiYWFicmFtb3Y5MCIsImEiOiJja2k5aHQ4ZWswZnhmMnNtcDJ0b2FlZzdjIn0.QcpV6ynhO9mlLga7CvUJwA')

```


```{r, include = FALSE}
filter_for = function(dataset, type) {
  if (type == "micro") {
  dataset %>% filter(str_detect(vehicle_options, "[Bb]ike") | 
           str_detect(vehicle_options, "REVEL") | 
           str_detect(vehicle_options, "SCO")  |
           str_detect(vehicle_options, "MOP")   |
           str_detect(vehicle_options, "ELEC")  |
           str_detect(vehicle_options, "^E-")) %>% 
  filter(vehicle_options != "ESCOVATOR" & vehicle_options != "Bike" &
      str_detect(vehicle_options, "Dirt", negate = TRUE),
      str_detect(vehicle_options, "[Mm]otorbike", negate = TRUE)
           )
}

  else if (type == "bike") {
  dataset %>% filter(str_starts(vehicle_options, "[Bb]ike")) 
  }
}
```


```{r, include = F}
#Import
crash_dat = read_csv("./data/crash_dat.csv")

#Create month_df
month_df=
  tibble(
    month = 1:12,
    month_name = factor(month.name, ordered = TRUE, levels = month.name)
  )

bikes = 
  crash_dat %>%
  filter_for("bike") %>%
  filter(
    month %in% (3:10),
    number_of_cyclist_injured > 0
    ) %>%
  separate(crash_time, into = c("hour", "minute", "second"), sep = ":") %>%
  mutate(
    covid = as.factor(if_else(year < 2020, 'Pre-COVID', 'COVID')),
    vehicle_number = str_extract_all(vehicle_number, "\\d", simplify = TRUE),
    covid = fct_relevel(covid, 'Pre-COVID'),
    dow = fct_relevel(dow, "Sunday", "Saturday", "Friday", "Thursday", "Wednesday", "Tuesday")
  ) 

microveh = 
  crash_dat %>%
  filter_for("micro") %>%
  filter(
    month %in% (3:10),
    number_of_persons_injured > 0
    ) %>%
  separate(crash_time, into = c("hour", "minute", "second"), sep = ":") %>%
  mutate(
    covid = as.factor(if_else(year < 2020, 'Pre-COVID', 'COVID')),
    vehicle_number = str_extract_all(vehicle_number, "\\d", simplify = TRUE),
    covid = fct_relevel(covid, 'Pre-COVID'),
    dow = fct_relevel(dow, "Sunday", "Saturday", "Friday", "Thursday", "Wednesday", "Tuesday")
  ) 


```


Interactive Maps
=======================================================================

Column {.tabset data-width=400}
-----------------------------------------------------------------------

### Cyclist Injuries by Borough  / Pre-Post Covid

```{r, echo=FALSE}
map_cyclists_injured=  crash_dat %>% 
  filter(
    str_detect(vehicle_options, "[Bb]ike"),
    number_of_cyclist_injured > 0) %>%
  mutate(
    covid = as.factor(if_else(year == 2019, 'Pre-COVID', 'COVID')),
    text_label = str_c("Crash Time: ", covid)) %>% 
  plot_mapbox(
    lon = ~longitude, 
    lat = ~latitude, 
    split = ~borough, 
    color = ~covid,
    mode = 'markers',
    text = ~text_label) %>% 
  layout(
    mapbox = 
      list(
        style = 'dark',
        zoom = 9.5, 
           center = list(lat = 40.71, lon = -73.97)),
    title = "Cyclist Injuries in NYC \nPre and Post Covid")

map_cyclists_injured %>% config(mapboxAccessToken = Sys.getenv("MAPBOX_TOKEN"))

#Here we're looking 2017-2020 instead - check w/Alexey
```




### Microvehicles with People Injured

```{r, echo=FALSE}
crash_map_microvehicles = 
  crash_dat %>% 
  filter(
    number_of_persons_injured > 0)   %>%
  mutate(
    covid = as.factor(if_else(year == 2019, 'Pre-COVID', 'COVID')),
    text_label = 
      str_c("Time Period: ", covid)) %>% 
  plot_mapbox(
    x = ~longitude, 
    y = ~latitude) %>% 
  add_polygons(
    color = ~borough,
    text = ~text_label) %>% 
  layout(
    mapbox = 
           list(
             style = "light",
             zoom = 9.5, 
             center = list(lat = 40.71, lon = -73.97)),
    title = "Microvehicle Injuries in NYC \nPre and Post Covid")

crash_map_microvehicles

```



### Density of Bicycle Crashes with Cyclists Injured During Covid

```{r, echo=FALSE}
 crash_dat %>%  
  filter_for("bike") %>% 
  drop_na(c(latitude, longitude, borough)) %>% 
  filter(number_of_cyclist_injured > 0) %>% 
  mutate(
    covid = as.factor(if_else(year == 2019, 'Pre-COVID', 'COVID')),
    text_label = str_c("Time Period: ", covid))  %>% 
  filter(
    covid == "COVID"
  ) %>% 
  plot_ly(
    lon = ~longitude, 
    lat = ~latitude,  
    type = 'densitymapbox',
    radius = 3,
    text = ~covid,
    hoverinfo = 'text') %>% 
  layout(
    mapbox = 
      list(
        style = 'open-street-map',
        zoom = 9.5,
        center = list(lat = 40.71, lon = -73.97)),
      title = "Density of Bicycle Crashes \n During Covid in NYC")


```


### Density of Bicycle Crashes with Cyclists Injured Prior to Covid

```{r, echo=FALSE}
crash_dat %>%  
  filter_for("bike") %>% 
  drop_na(c(latitude, longitude, borough)) %>% 
  filter(number_of_cyclist_injured > 0) %>% 
  mutate(
    covid = as.factor(if_else(year == 2019, 'Pre-COVID', 'COVID')),
    text_label = str_c("Time Period: ", covid))  %>% 
  filter(covid == "Pre-COVID") %>% 
  plot_ly(
    lon = ~longitude, 
    lat = ~latitude,  
    type = 'densitymapbox',
    radius = 3,
    text = ~covid,
    hoverinfo = 'text') %>% 
  layout(
    mapbox = 
      list(
        style = 'open-street-map',
        zoom = 10.5,
        center = list(lat = 40.71, lon = -73.97)),
      title = "Density of Bicycle Crashes \n Prior to Covid in NYC")

#let's fix the titles here


```



Incidents over Time
=======================================================================

Row
-----------------------------------------------------------------------

### Title 1

```{r}

```

### Title 2

```{r}

```

Row
-----------------------------------------------------------------------

### Title 3

```{r}

```

### Title 4

```{r}

```
   
   
Contributing Factors
=======================================================================


Column {.tabset .tabset-fade}
-------------------------------------
    
### Contributing Factors Bikes
```{r contributing_factor_bike, echo = FALSE, message = FALSE, warning = FALSE, fig.width=8}

top_10_bike = crash_dat %>%
  filter_for("bike") %>%
  filter(
    month %in% (3:10),
    number_of_cyclist_injured > 0
    ) %>%
  separate(crash_time, into = c("hour", "minute", "second"), sep = ":") %>%
  mutate(
    covid = as.factor(if_else(year < 2020, 'Pre-COVID', 'COVID')),
    vehicle_number = str_extract_all(vehicle_number, "\\d", simplify = TRUE),
    covid = fct_relevel(covid, 'Pre-COVID'),
    dow = fct_relevel(dow, "Sunday", "Saturday", "Friday", "Thursday", "Wednesday", "Tuesday")
  ) %>% 
  pivot_longer(
    contributing_factor_vehicle_1:contributing_factor_vehicle_5,
    names_to = "vehicle_factor_num",
    names_prefix = "contributing_factor_vehicle_",
    values_to = "contributing_factor"
   ) %>%
  mutate(
    contributing_factor = if_else(contributing_factor == "Pedestrian/Bicyclist/Other Pedestrian Error/Confusion", "Pedestrian/Cyclist Error", contributing_factor)
  ) %>%
  group_by(covid, contributing_factor) %>%
  summarise(
    collisions = n_distinct(collision_id)
  ) %>%
  drop_na(contributing_factor) %>%
  ungroup(contributing_factor) %>%
  filter(contributing_factor != "Unspecified") %>%
  mutate(
    covid = fct_relevel(covid, 'Pre-COVID'),
    proportion = round(collisions / sum(collisions), 2) 
  ) %>%
  group_by(covid) %>%
  top_n(n = 10, wt = proportion) %>%
  mutate(
    contributing_factor = fct_reorder(as.factor(contributing_factor), collisions, .desc = TRUE)
  ) %>%
  ggplot(aes(x = contributing_factor, y = proportion, fill = covid)) +
  geom_bar(stat = "identity") +
  facet_grid( . ~covid, scales = "free_x", space = "free_x") +
  scale_y_continuous(labels = scales::percent) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), legend.position = "none") +
  labs(
    title = "Top Ten Contributing Factors for Crashes Involving Injuries to Cyclists",
    x = "",
    y = ""
  ) 


ggplotly(top_10_bike, tooltip = c("x", "y")) 
```


### Contributing Factors Microvehicle
    
```{r contributing_factor_micro, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8}
top_10_micro = microveh %>%
  pivot_longer(
    contributing_factor_vehicle_1:contributing_factor_vehicle_5,
    names_to = "vehicle_factor_num",
    names_prefix = "contributing_factor_vehicle_",
    values_to = "contributing_factor"
   ) %>%
  mutate(
    contributing_factor = if_else(contributing_factor == "Pedestrian/Bicyclist/Other Pedestrian Error/Confusion", "Pedestrian/Cyclist Error", contributing_factor)
  ) %>%
  group_by(covid, contributing_factor) %>%
  summarise(
    collisions = n_distinct(collision_id)
  ) %>%
  drop_na(contributing_factor) %>%
  ungroup(contributing_factor) %>%
  filter(contributing_factor != "Unspecified") %>%
  mutate(
    covid = fct_relevel(covid, 'Pre-COVID'),
    proportion = round(collisions / sum(collisions), 2) 
  ) %>%
  group_by(covid) %>%
  top_n(n = 10, wt = proportion) %>%
  mutate(
    contributing_factor = fct_reorder(as.factor(contributing_factor), collisions, .desc = TRUE)
  ) %>%
  ggplot(aes(x = contributing_factor, y = proportion, fill = covid)) +
  geom_bar(stat = "identity") +
  facet_grid( . ~covid, scales = "free_x", space = "free_x") +
  scale_y_continuous(labels = scales::percent) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), legend.position = "none") +
  labs(
    title = "Top Ten Contributing Factors for Microvehicle Crashes Involving Injuries",
    x = "",
    y = ""
  )

ggplotly(top_10_micro, tooltip = c("x", "y")) 
```
 
 
 

### Heat maps - Bike
```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 8}

heat_maps = function(dataset, title) {
  pre = 
  dataset %>%
  filter(covid == "Pre-COVID") %>%
  plot_ly(
    x = ~hour, y = ~dow, z = ~collisions, type = "heatmap", colors = "BuPu"
  ) %>%
  colorbar(title = "Pre-COVID", x = 1, y = 1) 

covid = 
  dataset %>%
  filter(covid == "COVID") %>%
  plot_ly(
    x = ~hour, y = ~dow, z = ~collisions, type = "heatmap", colors = "YlGn"
  ) %>%
  colorbar(title = "COVID", x = 1, y = 0.5) 

subplot(pre, covid, nrows = 2, margin = .05) %>%
  layout(title = title)
}


crash_day_time = 
  bikes %>%
  group_by(covid, hour, dow) %>%
  summarise(
    collisions = n_distinct(collision_id)
  )  

p = heat_maps(dataset = crash_day_time, title = "Heat Maps of Bike Crashes")

ggplotly(p, tooltip = c("x", "y")) 
```

### Heat maps - Cyclists
```{r, echo = FALSE}
bikes %>%
  pivot_longer(
    contributing_factor_vehicle_1:contributing_factor_vehicle_5,
    names_to = "vehicle_factor_num",
    names_prefix = "contributing_factor_vehicle_",
    values_to = "contributing_factor"
   ) %>%
  filter((contributing_factor == "Pedestrian/Cyclist Error" |
           vehicle_factor_num == vehicle_number),
         contributing_factor != "Unspecified") %>%
  group_by(covid, hour, dow) %>%
  summarise(
    collisions = n_distinct(collision_id)
  ) %>% heat_maps(title = "Heat Maps of Bike Crashes Involving Cyclist Factors")
```

### Heat maps - Distraction
```{r, echo = FALSE}

  bikes %>%
  pivot_longer(
    contributing_factor_vehicle_1:contributing_factor_vehicle_5,
    names_to = "vehicle_factor_num",
    names_prefix = "contributing_factor_vehicle_",
    values_to = "contributing_factor"
   ) %>%
  filter(
    contributing_factor == "Driver Inattention/Distraction"
    ) %>%
  group_by(covid, hour, dow) %>%
  summarise(
    collisions = n_distinct(collision_id)
  ) %>% heat_maps(title = "Heat Maps of Bike Crashes Involving Driver Inattention")
```

### Heat maps - Microvehicle
```{r, echo = FALSE}
  microveh %>%
  group_by(covid, hour, dow) %>%
  summarise(
    collisions = n_distinct(collision_id)
  ) %>% heat_maps(title = "Heat Maps of Microvehicle Crashes")
```

   
Statistical Models
=======================================================================

Column {.tabset data-width=650}
-----------------------------------------------------------------------

### Possion Regression On Bike-Injuries

```{r, echo = FALSE, fig.width=9, fig.height=7}

crash_dat%>%
  filter_for("bike") %>% 
  filter(year %in% c(2019, 2020)) %>%
  group_by(year) %>%
  mutate(year_2020 = year - 2019) %>%
  nest(data = -month) %>%
  mutate(models = map(data, ~glm(number_of_persons_injured ~ year_2020:borough,
                                 family = "poisson", data = .x)),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest(models) %>%
  select(month, term, estimate, std.error, p.value) %>% 
  mutate(term = str_replace(term, "year_2020:borough", "2020 v. 2019, Borough: ")) %>%
  left_join(month_df, by = "month") %>%
  select(-month) %>%
  rename(month = month_name) %>%
  select(month, everything()) %>% 
  filter(term != "(Intercept)" & month != "November" & month != "December") %>%
  mutate(term = str_replace(term, "2020 v. 2019, ", "")) %>%
  ggplot(aes(x = month, y = exp(estimate), color = term)) + 
  geom_point(show.legend = FALSE, aes(size = estimate, alpha = .7)) +
  geom_errorbar(aes(ymin = exp(estimate - (1.96*std.error)), 
                    ymax = exp(estimate + (1.96*std.error)))) +
  geom_hline(yintercept = 1, linetype="dashed", 
                color = "darkred", size = 1, alpha = .7) +
  labs(
    title = "Difference in Rate of Injuries Per Crash Involving a Bike in 2020 v. 2019",
    x = "Month",
    y = "2020 v. 2019 Difference"
  ) +
  ylim(0, 5) +
  theme(legend.title = element_blank(),
        text = element_text(size = 10),
        axis.text.x = element_text(angle = 60, hjust = 1, size = 8)) + 
  facet_grid(. ~ term)


```

### Possion Regression On Microvehicle-Injuries

```{r, echo = FALSE, fig.width=9, fig.height=7}
crash_dat %>%
  filter_for("micro") %>% 
  filter(year %in% c(2019, 2020)) %>%
  group_by(year) %>%
  mutate(year_2020 = year - 2019) %>%
  nest(data = -month) %>%
  mutate(models = map(data, ~glm(number_of_persons_injured ~ year_2020:borough,
                                 family = "poisson", data = .x)),
         models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest(models) %>%
  select(month, term, estimate, std.error, p.value) %>% 
  mutate(term = str_replace(term, "year_2020:borough", "2020 v. 2019, Borough: ")) %>%
  left_join(month_df, by = "month") %>%
  select(-month) %>%
  rename(month = month_name) %>%
  select(month, everything()) %>% 
  filter(term != "(Intercept)" & month != "November" & month != "December") %>%
  mutate(term = str_replace(term, "2020 v. 2019, ", "")) %>%
  ggplot(aes(x = month, y = exp(estimate), color = term)) + 
  geom_point(show.legend = FALSE, aes(size = estimate, alpha = .7)) +
  geom_errorbar(aes(ymin = exp(estimate - (1.96*std.error)), 
                    ymax = exp(estimate + (1.96*std.error)))) +
  geom_hline(yintercept = 1, linetype="dashed", 
                color = "darkred", size = 1, alpha = .7) +
  labs(
    title = "Difference in Rate of Injuries Per Crash Involving a Microvehicle in 2020 v. 2019",
    x = "Month",
    y = "2020 v. 2019 Difference"
  ) +
  ylim(0, 5) +
  theme(legend.title = element_blank(),
        text = element_text(size = 10),
        axis.text.x = element_text(angle = 60, hjust = 1, size = 8)) + 
  facet_grid(. ~ term)
```

