---
title: "NYC Microvehicles: Final Project Proposal"
date: "11/6/2020"
output: 
  html_document:
  always_allow_html: true
---

### Group members:
Emma Gorin - emg2237, Sarah Conderino - sec2209, Talea Cornelius - tmc2184, Alexey Abramov - aa3832, Binyam Yilma - by2287

### Project title:
Collisions involving microvehicles in New York City in the past year

### Motivation for project and intended final products:
New Yorkers' transportation habits have changed over the past year. We’re interested in exploring the use of and crashes involving microvehicles (such as e-bikes and e-scooters) and, tentatively, bicycles in the context of the Covid-19 pandemic and the roll-out of Revel. To that end, we'd like to create an interactive dashboard of data visualizations related to use of microvehicles and crashes involving such vehicles.

### Anticipated data sources

* Main dataset - motorvehicle collisions: https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Crashes/h9gi-nx95
* Datasets on MTA use for context: https://data.cityofnewyork.us/Transportation/MTA-Data/mmu8-8w8b (also, metrocard swipe dataset: http://web.mta.info/developers/fare.html)
* Datasets on traffic and bicycle volume: https://data.cityofnewyork.us/Transportation/Traffic-Volume-Counts-2014-2019-/ertz-hr4r , https://data.cityofnewyork.us/Transportation/Bicycle-Counts/uczf-rk3c
* NOAA dataset to consider weather factors: https://w2.weather.gov/climate/xmacis.php?wfo=okx 
* EMS incident data to further examine crashes: https://data.cityofnewyork.us/Public-Safety/EMS-Incident-Dispatch-Data/76xm-jjuj

### The planned analyses / visualizations / coding challenges

* Visualizations: usage of microvehicles, bikes, public transit over time (labelling key moments in the timeline of the Covid-19 lockdown), maps of collisions, visualization considering weather variables
* Coding challenges: incomplete data, lack of granularity in how microvehicles are classified (Revel vs. personally owned)

### Anticipated Timeline:

* November 7: Create shared Github repository, submit project proposal
* November 8-12: Finalized list of data visualizations, delegate responsibilities
* November 13-21: Data cleaning (Import and tidy MV data, import and tidy NOAA data, merge datasets, generate descriptives)
* November 22-30: Create Visualizations (interactive descriptives, interactive plots)
* December 1-4: Clean and annotate final code, create cohesive dashboard, proofread and test for glitches
* December 5: Final project due

 
 